title: KOMJI BLOG
description: 어제 뭐했는지 기억못하는 청년의 기억소
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/views/posts/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed